// Generated by https://quicktype.io

export interface Count248NextHTTPSPokeapiCoAPIV2AbilityLimit20Offset20PreviousNullResultsNameStenchURLHTTPSPokeapiCoAPIV2Ability1 {
  count: number;
  next: string;
  previous: null;
  results: Result[];
}

export interface Result {
  name: string;
  url: string;
}
